import { fieldsData } from "@/types/FieldsDataTypes";

const MarksGrading: fieldsData[] = [
    {
        id: 0,
        name: "foraplus",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
        
    },
    {
        id: 1,
        name: "aplusfrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 2,
        name: "aplusupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
    },
    {
        id: 3,
        name: "aplusposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
    {
        id: 4,
        name: "fora",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
    },
    {
        id: 5,
        name: "afrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 6,
        name: "aupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
    },
    {
        id: 7,
        name: "aposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
    {
        id: 8,
        name: "forBplus",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
        value: "",
    },
    {
        id: 9,
        name: "bplusfrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 10,
        name: "bplusupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
        value: 69,
    },
    {
        id: 11,
        name: "bplusposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
    {
        id: 12,
        name: "forb",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
        value: "B",
    },
    {
        id: 13,
        name: "bfrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 14,
        name: "bupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
    },
    {
        id: 15,
        name: "bposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
    {
        id: 16,
        name: "forc",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
    },
    {
        id: 17,
        name: "cfrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 18,
        name: "cupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
    },
    {
        id: 19,
        name: "cposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
    {
        id: 20,
        name: "ford",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
    },
    {
        id: 21,
        name: "dfrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 22,
        name: "dupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
    },
    {
        id: 23,
        name: "dposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
    {
        id: 24,
        name: "forf",
        theme: "blues",
        type: "text",
        select: false,
        label: "Grade*",
    },
    {
        id: 25,
        name: "ffrom",
        theme: "blues",
        type: "number",
        select: false,
        label: "% From*",
    },
    {
        id: 26,
        name: "fupto",
        theme: "blues",
        type: "number",
        select: false,
        label: "% Upto*",
    },
    {
        id: 27,
        name: "fposition",
        theme: "blues",
        type: "text",
        select: false,
        label: "Status*",
    },
]

export default MarksGrading;